### ISSUE TITLE
Can you share BeRo Tiny Pascal on GitHub?

### ISSUE THREAD

**Issue by Mazdaywik** [BeRo1985/crosspascal#2]
At 2006 year you had written self-applicable Pascal compiler — BeRo Tiny Pascal. It has simple and compact full source code and is best for teaching students on compiler development course. Can you share the compiler on GitHub with open source license agreement (BSD, MIT, GNU or other)?

I am a teacher in [BMSTU](http://www.bmstu.ru/en/) and I want use BeRo Tiny Pascal in my work legally (i. e. with open source license written by author).

P.S. Sorry for my English.

**Comment by BeRo1985** [comment]
Done => https://github.com/BeRo1985/berotinypascal which's zlib-licensed now :-)

**Comment by Mazdaywik** [comment]
Thanks!

**Comment by Mazdaywik** [comment]
I replaced old unlicensed compiler to new in my course tasks:

bmstu-iu9/compiler-labs@8b3cf1664bfbedf34f8fe57c88f6ce26e0899883

Thank you for refactoring source code and add descriptive error messages!
